### ISSUE TITLE
Copyright should read "Rightpoint"

### ISSUE THREAD

**Issue by jkaufman** [Rightpoint/ios-template#114]
Copyright should read "Rightpoint"

**Comment by minimusic** [comment]
Should the year (Copyright 2016 Rightpoint) be left as is, or brought forward to year of acquisition (2017), or to now (2019)?

**Comment by minimusic** [comment]
And where are you seeing the copyright? I'm seeing it mostly for pods (Anchorage, BonMot, Swiftilities). The template files are all replaced by cookie cutter: "Copyright © 2017 ORGANIZATION"

**Comment by minimusic** [comment]
I guess it is in `LICENSE` file at root...

**Comment by minimusic** [comment]
in https://github.com/Rightpoint/ios-template/pull/141
