### ISSUE TITLE
Update install_provisioning_profiles plugin

### ISSUE THREAD

**Issue by ZevEisenberg** [Rightpoint/ios-template#118]
In here (and possibly other places): https://github.com/Rightpoint/ios-template/blob/f0e9c6e26656d65bcaf2dbaef13ba29686876684/PRODUCTNAME/app/fastlane/Pluginfile

Per [this comment](https://github.com/dgyesbreghs/install_provisioning_profiles/issues/4#issuecomment-487257194), there's a new version that should fix issues we were having.

**Comment by chrisballinger** [comment]
This should be resolved by #119
