### ISSUE TITLE
Move BUILD_NUMBER=1 up to global config

### ISSUE THREAD

**Issue by ZevEisenberg** [Rightpoint/ios-template#136]
Currently, we have `BUILD_NUMBER=1` in Debug.xcconfig. This is to placate Xcode, which validates that the app has a valid build number when running in the simulator. During a real build, Fastlane generates and injects a build number.

We should move the local override up to Global.xcconfig so it applies to all schemes, not just the Debug scheme. The build number will still be overridden by the argument passed in by Fastlane, so this would just make it possible to run the other schemes on the simulator.

Credit to @chrisballinger with the idea.

**Comment by minimusic** [comment]
Done in: https://github.com/Rightpoint/ios-template/pull/137
